### ISSUE TITLE
Reference "Data" directory should be "data"

### ISSUE THREAD

**Issue by nedhorning** [GatorGlaciology/GStat-Sim#15]
The first line in code block 3 of Notebook 9_cokriging_and_cosimulation_MM1.ipynb  the line with ‘Data/greenland_surface_data.csv’ should be changed to ‘data/greenland_surface_data.csv’

Great resource by the way!

**Comment by GatorGlaciology** [comment]
Thanks for the feedback! We'll update it shortly
