### ISSUE TITLE
Reshape error running mplot2_std from plot_utils.py

### ISSUE THREAD

**Issue by nedhorning** [GatorGlaciology/GStat-Sim#18]
I'm getting this error when running mplot2_std from plot_utils.py using my dataset. It looks like the value returned from prediction_grid does not match rows * cols. Here is the error: cannot reshape array of size 78952 into shape (278,283)

I'll try to dig into this to see if I can find the problem. I tried to delete this issue until I have more information but wasn't able to do that.

**Comment by trivediashutosh** [comment]
I am unable to import splot2D, mplot1, mplot2_std, make_colorbar from plot_utils. How did you imported it?

**Comment by GatorGlaciology** [comment]
We've removed plot_utils from the package and updated the tutorials so that the plots are created from scratch
