### ISSUE TITLE
Rounding in gstatsim.make_grid causes np.reshape error

### ISSUE THREAD

**Issue by pandaPG** [GatorGlaciology/GStat-Sim#23]
https://github.com/GatorGlaciology/GStatSim/blob/36f627c66bd7c84de3a5673f7850fee06f56714c/gstatsim.py#L93

#### Description: 
The rounding proceture in the function make_grid(xmin, xmax, ymin, ymax, res) leads to a dimension mismatch when np.reshape is applied.  More precisely, the rounding done for cols (rows) does not match the size of x (y) and hence xx (yy) does not have the dimension rows*cols. 

#### Toy-Example:
```
xmax=30
xmin=10
ymax=30
ymin=10
res=80

prediction_grid_xy, cols, rows=make_grid(xmin, xmax, ymin, ymax, res)
```
## Error:

> ValueError: cannot reshape array of size 1 into shape (0,1)

## Reproduce Error:
```
xmax=30
xmin=10
ymax=30
ymin=10
res=80

cols = np.rint((xmax - xmin)/res) 
rows = np.rint((ymax - ymin)/res)  
rows = rows.astype(int)
cols = cols.astype(int)
x = np.arange(xmin,xmax,res); y = np.arange(ymin,ymax,res)
xx, yy = np.meshgrid(x,y) 

print(cols*rows)
print(x.size*y.size)
print(xx.size)
```
## Output:

> 0
> 1
> 1

So the error accures here:
```
x = np.reshape(xx, (int(rows)*int(cols), 1)) 
y = np.reshape(yy, (int(rows)*int(cols), 1))
```

#### Suggestion

Maybe define cols and rows like this:

```
cols = np.ceil((xmax - xmin)/res) 
rows = np.ceil((ymax - ymin)/res) 

```

**Comment by GatorGlaciology** [comment]
Thanks for highlighting this! We'll work on fixing this issue. In the meantime, if this bug is holding your work back, you can make your own interpolation grid however you choose. Our interpolation functions just require an array of input coordinates.

**Comment by GatorGlaciology** [comment]
Fixed!
