### ISSUE TITLE
`Gridding.prediction_grid` changed output

### ISSUE THREAD

**Issue by mmaelicke** [GatorGlaciology/GStat-Sim#24]
Hi guys,

With an upgrade of GStatSim from `1.0.4` to `1.0.6` the `Gridding.prediction_grid` seems to produce different output.

Within the SciKit-GStat  unittests, I run a check very similar to the minimal example below:

```python
import gstatsim as gs
gs.Gridding.prediction_grid(8, 481, 21, 487, 5).shape. 
```

In version `1.0.4` this returned `(9024, 2)`, while in version `1.0.6` the result is `(9120, 2)`.

Is this intentionally, was there a bug?  Are you aware? 
Could you give me some background on this issue, as I am actively working on the Gstatsim interface for SciKit-GStat again.

Best,

Mirko

**Comment by GatorGlaciology** [comment]
Yes, we updated the gridding function because of a bug (the way we rounded the number of rows and columns was causing reshaping errors with certain inputs). So the new version might have slightly different grid sizes. Let us know if you run into any problems with the new version.
